name: SimpleChairs
version: @version@
main: com.cnaude.chairs.core.Chairs
api-version: 1.16
authors:
  - spoothie
  - cnaude
  - _Shevchik_
  - Pugabyte
description: A simpler fork of Shevchik's amazing Chairs plugin.
website: https://github.com/ItsTehBrian/SimpleChairs
commands:
  chairs:
    description: Various commands for SimpleChairs.
    usage: |
      /<command> reload - reload the configuration
      /<command> off - disable chairs for self
      /<command> on - enable chairs for self
permissions:
  chairs.*:
    description: Gives access to all Chairs commands
    children:
      chairs.sit: true
      chairs.reload: true
  chairs.reload:
    description: Allows you to reload Chairs Configuration
    default: op
  chairs.sit:
    description: Allows you to sit on a chair
    default: true